name: Check for repo update and trigger update workflow

on:
  workflow_dispatch:
    inputs:
      repository:
        description: Repository to update
        required: true
        type: choice
        options:
          - LibreELEC/amlogic-boot-fip
          - LibreELEC/brcmfmac_sdio-firmware
          - LibreELEC/dt-overlays
          - LibreELEC/dvb-firmware
          - LibreELEC/eventlircd
          - LibreELEC/iwlwifi-firmware
          - LibreELEC/meson-firmware
          - LibreELEC/misc-firmware
          - LibreELEC/script.config.vdr
          - LibreELEC/service.libreelec.settings
          - LibreELEC/wlan-firmware

jobs:
  check-package-update:
    runs-on: ubuntu-24.04
    if: github.repository == 'LibreELEC/actions'
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout LibreELEC.tv
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          repository: LibreELEC/LibreELEC.tv
          path: LibreELEC-upstream

      - name: Get latest commit hash from the repository
        id: set-matrix
        shell: bash
        env:
          REPO: ${{ github.event.inputs.repository }}
        run: |
          echo "Selected repo: $REPO"
          REPO_NAME=$(echo "$REPO" | cut -d'/' -f2)
          case "$REPO" in
            "LibreELEC/service.libreelec.settings")
              REPO_NAME="LibreELEC-settings"
              ;;
          esac
          updated_packages="${REPO_NAME}"
          pair=$(echo "$updated_packages" | jq -Rn -c '[inputs | split(" ")] | map({ name: .[0], version: (.[1] // "") })')
          echo "matrix=$pair" >> $GITHUB_OUTPUT

      - name: Job summary
        shell: bash
        run: |
          echo "### 📌 Updating these Packages" >> $GITHUB_STEP_SUMMARY
          {
            echo "| Package | Version |"
            echo "|---------|---------|"
            echo '${{ steps.set-matrix.outputs.matrix }}' | jq -r '.[] | "| \(.name) | \(.version) |"'
          } >> "$GITHUB_STEP_SUMMARY"

  call-package-update:
    needs: check-package-update
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.check-package-update.outputs.matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          repository: LibreELEC/actions

      - name: Log matrix entry
        run: |
          echo "Package:  ${{ matrix.name }}"
          echo "Version:  ${{ matrix.version }}"

      - name: Package version bump and PR
        uses: ./.github/actions/package_version_bump_and_pr_changes
        env:
          GH_TOKEN: ${{ secrets.LEBOT_PAT }}
          LEBOT_TOKEN: ${{ secrets.LEBOT_PAT }}
        with:
          PACKAGE_NAME: ${{ matrix.name }}
          PACKAGE_VERSION: ${{ matrix.version }}
          IS_REPO: yes
          GIT_TOKEN: ${{ secrets.LEBOT_PAT }}
